on: [push]

name: build

jobs:
  check:
    name: check build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
           targets: wasm32-unknown-unknown

      - name: Install protoc compiler
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
           version: 'latest'

      - run: |
          cargo check
          cargo build
          wasm-pack build --release --target web
